name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        working-directory: ./front
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        working-directory: ./front
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        working-directory: ./front
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Lint the Project
        working-directory: ./front
        run: npm run lint
      - name: Deploy Project Artifacts to Vercel
        working-directory: ./front
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}


  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        working-directory: ./front
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        working-directory: ./front
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
